### ISSUE TITLE
Documenter Version

### ISSUE THREAD

**Issue by tt1234567** [ltjkoomen/FIRLSFilterDesign.jl#4]
Hi - thanks for a very useful package. I think there's a minor problem in that, for me,  FIRLSFilterDesign is holding up the upgrade of other packages - something to do with the version of Documenter in the project.toml compat section. Documenter is now at v 0.27.24. I don't really understand these things otherwise I'd try and do a PR myself.

**Comment by tt1234567** [comment]
Ah! It looks like there's already an automated PR. That's clever!

**Comment by ltjkoomen** [comment]
Thanks! I've merged the Documenter PR. This should fix the issue, closing.

**Comment by tt1234567** [comment]
Thanks! Do you need to do a new release for the Julia registry to pick up the changes? I don't quite understand how it's supposed to happen but the change doesn't seem to have got through yet.
